export const quizActionTypes = {
  SET_TOTAL_NUM_QUESTIONS: 'SET_TOTAL_NUM_QUESTIONS',
  INCREMENT_CURRENT_QUESTION_IDX: 'INCREMENT_CURRENT_QUESTION_IDX',
  INCREMENT_NUMBER_CORRECT: 'INCREMENT_NUMBER_CORRECT',
  SHUFFLE_AND_SET_CHOICES: 'SHUFFLE_AND_SET_CHOICES',
  TOGGLE_SHOW_SUMMARY: 'TOGGLE_SHOW_SUMMARY',
  RESET_STATE: 'RESET_STATE',
};
